### ISSUE TITLE
expires_module disabled

### ISSUE THREAD

**Issue by kossa** [algeriatech/algeria-meetup#18]
@hlagrid, the website hosted on VPS or shared host ?

**Comment by hlagrid** [comment]
Hosted on github with a linked domain name :
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/
So, we don't have access to any config, I'm not sure if we can force the activation via an .htaccess file

**Comment by kossa** [comment]
Ahh ok i see i'm not dure that's possible

**Comment by kossa** [comment]
I think is not possible :)
