### ISSUE TITLE
A static XML file to store all the informations we need about our meetups

### ISSUE THREAD

**Issue by ahsio** [algeriatech/algeria-meetup#3]
I think better is to use a static XML file to add information about the event, we'll just have to add an entry with the date, the topic, the speakers, ..etc and then it automatically updates the website.

Exemple:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<meetups>
   <meetup id="1">
     <date></date>
     <location></location>
     <topic></topic>
     <presentations>
       <presentation>
         <speakers>
           <speaker>
             <fullname></fullname>
             <title></title>
             <slides></slides>
           </speaker>
         </speakers>
       </presentation>
       <presentation>
         <!-- ... -->
       </presentation>
     </presentation>
   </meetup>  
   <meetup id=2>
     <!-- ... -->
   </meetup>
</meetups>
```

This is just a first draft, we can make an xsd file that do fit the structure we want to store all the relevant informations we need for our meetups.

This approach will help us,
- Avoid editing the code each time we need to update the website for a new meetup
- Provide a structured static data content about our activities that can be converted to any other format
  and also used as a data source elsewhere.

**Comment by hlagrid** [comment]
Totally agree with you @ahsio it's really imporant to separate the data, it will help too much for the update.

**Comment by ahsio** [comment]
@hlagrid I'll work on it! The main constraint here is to help the moderators on editing the content.
After thinking twice about the format we should use, I would suggest Yaml, as it's visually easier to read and to understand,

The previous example would then look like,

<pre>
meetups:
    meetup:
        date: xx / xx / xxxx
        location: xxxxxx
        topic: xxxxxx
        presentations:
             presentation:
                 speakers:
                     speaker:
                         fullname: xxxxxx
                         title: xxxxxx
                         slides: http://xxxxxx
# ...         
</pre>

Does this sound good for you ?

**Comment by IOAyman** [comment]
:+1: @ahsio

**Comment by hlagrid** [comment]
@ahsio yeah, Yaml is more human readable which means easy to edit, please go for it.

**Comment by rouabhi** [comment]
Hey guys,
why XML ? that's.. heu.. backward :o
Let's use JSON.. that is way more convenient and more.. Javascript !!

No ?

**Comment by oussaki** [comment]
i Agree with Mr rouabhi , JSON is more adequate .

**Comment by ahsio** [comment]
@rouabhi @oussaki Thanks guys but please read all the comments, we were never talking about "JSON versus XML dilemma" as a solution to store the data.

For sure JSON is javascript friendly, but the main constraint here is to make the data file human readable (as mentioned by @hlagrid). 

It's not <i>a technology driven feature</i> and we'll not use the right format only because it's easy to use for a given technology (for example, using JSON only because it's javascript friendly). We're working on improvements that are driven by <b>needs</b>, and <b>the main constraint</b> here is to provide a data file that can be updated by <b>everybody (even non-developers)</b>. And [Yaml](https://en.wikipedia.org/wiki/YAML) does fit this constraint. 

Do you have any other argument in favour of JSON and against Yaml, by taking into account the need of providing a human readable data file?

**Comment by rouabhi** [comment]
In favor of JSON ? I would say it is as easy to read (for an administrator)  as YAML..

I've never used YAML before but it seems like there are good standard libraries in almost all languages: javascript, PHP, C,... so it looks like it is a good choice. ;)

**Comment by hlagrid** [comment]
@ahsio any update for the website ?
