### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by ahsio** [algeriatech/algeria-meetup#7]
We should use angular to address the need of iterating through nested data structures used to build the website content. [A temporary fix](https://github.com/algiers-meetup/algiers-meetup.github.io/blob/master/js/meetup.js) was introduced for that but we should consider making a permanent fix using Angular.

**Comment by Moncef12** [comment]
If, just a declarative way is needed over the current one with jQuery, why not just use a simple template engine ?

Just an opinion :)

**Comment by g13013** [comment]
@Moncef12 and @ahsio we should care about SEO, I don't know much about angular, be if we use a templating engine we would need to address SEO problems unless we render all the stuff in back-end.

**Comment by Moncef12** [comment]
@g13013 You are right.  

I think for SEO we have to options ( btw for angularJS the second option is used ) : 
- Render (as you said) all the stuff in the backend.
- Use PhantomJS to pre-render/serve "just" for web crawlers (so two ports are needed : one for normal web site, the second for web site behind phantomJS).

**Comment by g13013** [comment]
Knowing that, I think it's too much complication for the size of the project

**Comment by Moncef12** [comment]
@g13013   +1

A simple template engine on the server will be enough.

**Comment by ahsio** [comment]
@Moncef12 @g13013 Thanks for the suggestions :)
- :+1: For taking care of SEO but as it's out of the scope of the current issue, feel free to open a new issue that aims to handle it, we'll then discuss possible solutions in this issue and then open a pull Request related to that issue.
- @Moncef12 What kind of simple template engine are you thinking about ? And how these simple template engines can help us handle iterating through nested data structures ? (which is the main idea behind the current issue)
- @Moncef12 What do you mean by rendering all the stuffs in the backend?
- Keep in mind guys that we're providing a website that <b>only</b> aims to publish informations about previous and upcoming meeting. It's as easy as abc. So, we should not be trapped by the dogma of turning a simple need to an experimental project, trying to introduce technologies that are usually used to handle issues that are out of the scope of our needs, (PhantomJS for example).

**Comment by Moncef12** [comment]
Hello @ahsio  :)

I will answer you questions in order   :
- Exemple of template engines  : Jade, handlebars, ...
- You can do this using a template engine. very easy in Jade,  for, handlebards, I think you must register another helper to get the current (this) scope.  @g13013 can confirm this. But, it should not be hard.
- For exemple Jade as template engine with Node.js in the backend, why ? web crawlers will not excute javascript. so, using jQuery/AngularJS/template engine it's just JS. Also, I agree (like @g13013  pointed out)  that the first page from web site, like this one, must be optimized to be well indexed.
- For the last point,  For, PhantomJS I "just" explained how to well index the page if you are going to use angularJS.
- Always for the last point, I agree with you when you say it's just a one page web site, this is why, I think that using just  one directive (ngRepeat) from a full framework is not a very good choice IMHO.

**Comment by g13013** [comment]
@ahsio welcome ! I agree with both of you, for this type of project I would recommend using only JQuery!

**Comment by ahsio** [comment]
@Moncef12 What do you think about @g13013 suggestion? I do agree with him. I was thinking about angular not only to use one directive. but also to make a true separation about all the website content (highlights, about, our chart, calendar, ...etc) and to clearly separate the logic of dynamically loading the content in controllers and services that are easy to maintain and to improve. But finally I think that we should keep it simple as the current implementation do the job. It should be improved when necessary.

Is it ok for you guys if I close the issue?

**Comment by Moncef12** [comment]
@ahsio sounds good for me :)  

(and totally agree with you to consider angularJS when website start growing).

Nothing to add for me on this issue.
